"""Optimize models and queries

Revision ID: ec2ec2fcb534
Revises: f128673da830
Create Date: 2026-05-12 00:10:59.693212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2ec2fcb534'
down_revision = 'f128673da830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EMPLOYEE', schema=None) as batch_op:
        batch_op.alter_column('DateHired',
               existing_type=sa.VARCHAR(length=345),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('PASSWORD_RECOVERY', schema=None) as batch_op:
        batch_op.alter_column('DateMade',
               existing_type=sa.VARCHAR(length=345),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('SERVICE_RECORD', schema=None) as batch_op:
        batch_op.alter_column('StartDate',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('StartTime',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('FinishDate',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('FinishTime',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SERVICE_RECORD', schema=None) as batch_op:
        batch_op.alter_column('FinishTime',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('FinishDate',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('StartTime',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.alter_column('StartDate',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('PASSWORD_RECOVERY', schema=None) as batch_op:
        batch_op.alter_column('DateMade',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=345),
               existing_nullable=False)

    with op.batch_alter_table('EMPLOYEE', schema=None) as batch_op:
        batch_op.alter_column('DateHired',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=345),
               existing_nullable=False)

    # ### end Alembic commands ###
